// ---- LIBRARIES
//= require "../../../app/javascripts/lib/simple-javascript-airbrake-notifier/notifier.js"
//= require "../../../app/javascripts/lib/jquery-1.8.2.min.js"
//= require "../../../app/javascripts/lib/jquery-ui-1.8.23.custom.min.js"
//= require "../../../app/javascripts/lib/swfobject-2.2.js"
//= require "../../../app/javascripts/lib/jquery-class-create/class.js"
//= require "../../../app/javascripts/lib/jquery-behaviors/behaviors.js"
//= require "../../../app/javascripts/lib/jquery.inview/jquery.inview.js"
//= require "../../../app/javascripts/lib/jquery-patches/src/xhr.js"
//= require "../../../app/javascripts/lib/jquery-patches/src/event.js"

window.$window   = $(window);
window.$document = $(document);

// ---- PROTONET
//= require "../../../app/javascripts/protonet/extensions.js"
//= require "../../../app/javascripts/protonet/protonet.js"
//= require "../../../app/javascripts/protonet/i18n/translate.js"
//= require "../../../app/javascripts/protonet/events/emitter.js"
//= require "../../../app/javascripts/protonet/utils/add_slashes.js"
//= require "../../../app/javascripts/protonet/utils/auto_link.js"
//= require "../../../app/javascripts/protonet/utils/prettify_code.js"
//= require "../../../app/javascripts/protonet/utils/codify.js"
//= require "../../../app/javascripts/protonet/utils/quotify.js"
//= require "../../../app/javascripts/protonet/utils/emojify.js"
//= require "../../../app/javascripts/protonet/utils/convert_to_absolute_url.js"
//= require "../../../app/javascripts/protonet/utils/deep_equal.js"
//= require "../../../app/javascripts/protonet/utils/template.js"
//= require "../../../app/javascripts/protonet/utils/escape_for_css_query.js"
//= require "../../../app/javascripts/protonet/utils/escape_for_reg_exp.js"
//= require "../../../app/javascripts/protonet/utils/escape_html.js"
//= require "../../../app/javascripts/protonet/utils/format_seconds.js"

// ---- PROTONET TESTS
//= require "i18n/i18n_test.js"
//= require "events/emitter_test.js"
//= require "utils/add_slashes_test.js"
//= require "utils/auto_link_test.js"
//= require "utils/codify_test.js"
//= require "utils/quotify_test.js"
//= require "utils/emojify_test.js"
//= require "utils/convert_to_absolute_url_test.js"
//= require "utils/deep_equal_test.js"
//= require "utils/escape_for_css_query_test.js"
//= require "utils/escape_for_reg_exp_test.js"
//= require "utils/escape_html_test.js"
//= require "utils/format_seconds_test.js"
