#!/bin/sh

HOST=protodeploy@deploy.flyingseagull.de
APPARCHIVE=dashboard_app.tar.bz2

tar --exclude '\.git*' --exclude '\._*' --exclude '*.psd' --exclude 'public/uploads/*' -cjvf $APPARCHIVE $CURRENT_PATH

scp $APPARCHIVE $HOST:deploy/assets

rm $APPARCHIVE