#!/bin/bash

export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export SHARED=$CURRENT_PATH/../../shared
export HOME=$CURRENT_PATH/../..
. $HOME/../.bashrc
. $HOME/../.profile
cd $SHARED
export SHARED=`pwd`

case $1 in
   start)
      /usr/sbin/monit -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid
      ;;
    stop)  
      /usr/sbin/monit -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid quit
      ;;
    restart)
      /usr/sbin/monit -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid restart all
      ;;
    reload)
      /usr/sbin/monit -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid reload
      ;;
    *)  
      echo "usage: app_monit {start|stop|restart|reload}" ;;
esac
exit 0