#!/bin/bash

export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export SHARED=$CURRENT_PATH/../../shared
export HOME=$CURRENT_PATH/../..
. $HOME/../.bashrc
. $HOME/../.profile
cd $SHARED
export SHARED=`pwd`

if [ -x /usr/sbin/monit ] ; then
  MONIT=/usr/sbin/monit
else
  MONIT=/usr/bin/monit
fi

case $1 in
   start)
      $MONIT -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid
      ;;
    stop)  
      $MONIT -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid quit
      ;;
    restart)
      $MONIT -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid restart all
      ;;
    reload)
      $MONIT -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid reload
      ;;
    status)
      $MONIT -c $SHARED/config/monit_ptn_node -l $SHARED/log/monit.log -p $SHARED/pids/monit.pid status
      ;;
    *)  
      echo "usage: app_monit {start|stop|restart|reload|status}" ;;
esac
exit 0