#!/bin/bash

export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export SHARED=$CURRENT_PATH/../../shared
export HOME=$CURRENT_PATH/../..
. $HOME/../.bashrc
. $HOME/../.profile
cd $SHARED
export SHARED=`pwd`
export IPT=/sbin/iptables
# the interface with the internetz
export EXTIF=$1
# the interface with the local or captivated clients
export INTIF=$2
export REDIRECTION_TARGET=$3
export IPT_COMMENT="-m comment --comment protonet_captive"
shift 3
case $1 in
    start)
      if [ -z "`$IPT -L -t nat -v | grep unknown_user`" ]; then
        echo "No captive portal rules active, starting up."
      else
        echo "Firewall rules seem to be active, exiting!"
        exit 1
      fi
      echo "   External Interface:          $EXTIF"
      echo "   Internal Interface:          $INTIF"
      
      echo "   Creating our unknown_user chain (handles traffic from public interface)"
      $IPT -N unknown_user -t nat
      
      echo "   manage traffic coming from the public interface.."
      # accept allow tcp:80, tcp:443, udp:67 (dhcp) and udp:53 (dns) and tcp:5000 (protonet-socket) requests
      $IPT -t nat -A PREROUTING -i $INTIF -p tcp -m tcp --destination $REDIRECTION_TARGET --dport 80   -j ACCEPT $IPT_COMMENT
      $IPT -t nat -A PREROUTING -i $INTIF -p tcp -m tcp --destination $REDIRECTION_TARGET --dport 443  -j ACCEPT $IPT_COMMENT
      $IPT -t nat -A PREROUTING -i $INTIF -p udp -m udp --destination $REDIRECTION_TARGET --dport 67   -j ACCEPT $IPT_COMMENT
      $IPT -t nat -A PREROUTING -i $INTIF -p udp -m udp --destination $REDIRECTION_TARGET --dport 53   -j ACCEPT $IPT_COMMENT
      $IPT -t nat -A PREROUTING -i $INTIF -p tcp -m tcp --destination $REDIRECTION_TARGET --dport 5000 -j ACCEPT $IPT_COMMENT
      $IPT -t nat -A PREROUTING -i $INTIF -p tcp -m tcp --destination $REDIRECTION_TARGET --dport 5001 -j ACCEPT $IPT_COMMENT

      echo "   send all public traffic to the unknown_user chain"
      $IPT -t nat -A PREROUTING -i $INTIF -j unknown_user $IPT_COMMENT

      echo "   and drop all forward pakets marked 99"
      $IPT -t filter -A FORWARD -i $INTIF -m mark --mark 99 -j DROP $IPT_COMMENT


      echo "   allow traffic from all stored (and authorized) mac addresses"
      touch $SHARED/config/ifconfig.d/allowed_clients
      chown protonet:protonet $SHARED/config/ifconfig.d/allowed_clients
      awk 'BEGIN { FS="\t"; } { system("$CURRENT_PATH/script/init/client_internet_access grant \"$2\" \"$1\" \"$4\""); }' $SHARED/config/ifconfig.d/allowed_clients

      echo "   mark all traffic from the unknown_user chain as 99 (untrusted)"
      $IPT -t nat -A unknown_user -j MARK --set-mark 99 $IPT_COMMENT

      echo "   redirect all traffic to $REDIRECTION_TARGET"
      $IPT -t nat -A unknown_user -m mark --mark 99 -p tcp --dport 80 -j DNAT --to-destination $REDIRECTION_TARGET $IPT_COMMENT
      # create file
      ;;
    stop)
      GRANTS_CMD="$IPT -L PREROUTING -t nat -v --line-numbers | grep protonet_captive | awk 'BEGIN { FS=\" \"; } {print \"$IPT -t nat -D PREROUTING \" \$1}' | sort -r | bash"
      echo $GRANTS_CMD | bash
      PREROUTING_CMD="$IPT -L unknown_user -t nat -v --line-numbers | grep protonet_captive | awk 'BEGIN { FS=\" \"; } {print \"$IPT -t nat -D unknown_user \" \$1}' | sort -r | bash"
      echo $PREROUTING_CMD | bash
      FORWARD_CMD="$IPT -L FORWARD -v --line-numbers | grep protonet_captive | awk 'BEGIN { FS=\" \"; } {print \"$IPT -t nat -D PREROUTING \" \$1}' | sort -r | bash"
      echo $FORWARD_CMD | bash
      $IPT -X unknown_user -t nat
      # remove file
      rm -f $SHARED/config/ifconfig.d/allowed_clients
      ;;
    status)
      if [ -z "`$IPT -L -t nat -v | grep unknown_user`" ]; then
        echo "Couldn't find the unknown_user chain, probably down."
        exit 1
      else
        echo "Firewall rules seem to be active."
        exit 0
      fi
      ;;
    *)  
      echo "usage: captive_portal internet_interface internal_interface redirection_target {start|status}" ;;
esac
exit 0
