#!/bin/bash

export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export SHARED=$CURRENT_PATH/../../shared
export HOME=$CURRENT_PATH/../..
. $HOME/../.bashrc
. $HOME/../.profile
cd $SHARED
export SHARED=`pwd`
export IPT=/sbin/iptables
export COMMAND=$1
shift 1
export MAC=$1
export USERNAME=$2

case $COMMAND in
   grant)
      echo "Granting internet access to $USERNAME, $MAC"
      $IPT -I unknown_user 1 -t nat -m mac --mac-source $MAC -j RETURN -m comment --comment "$USERNAME protonet_captive"
      ;;
    revoke)
      echo "Revoking internet access from $MAC"
      CMD="$IPT -L unknown_user -v -t nat --line-numbers | awk '/$MAC/ {print \"$IPT -t nat -D unknown_user \" \$1}' | sort -r | bash"
      
    echo $CMD | bash
      ;;
    list)
      $IPT -L unknown_user -v -t nat --line-numbers | grep protonet_captive | awk 'BEGIN { FS="      "; } { print $6}'
      ;;
    status)
      if $IPT -L unknown_user -v -t nat --line-numbers  | grep -q $MAC; then
        echo "Granted"
        exit 0
      else
        echo "Not Granted"
        exit 1
      fi
      ;;
    refresh)
      # here $1 is the ip address client and $2 is the ip of the node thru the current interface, see captive_controller for details
      /usr/sbin/conntrack -L | grep $1 | grep ESTAB | grep -v $2 | grep 'dport=80'  | awk "{ system(\"conntrack -D --orig-src $1 --orig-dst \" substr(\$6,5) \" -p tcp --orig-port-src \" substr(\$7,7) \" --orig-port-dst 80\"); }"
      /usr/sbin/conntrack -L | grep $1 | grep ESTAB | grep -v $2 | grep 'dport=443' | awk "{ system(\"conntrack -D --orig-src $1 --orig-dst \" substr(\$6,5) \" -p tcp --orig-port-src \" substr(\$7,7) \" --orig-port-dst 443\"); }"
      ;;
    *)  
      echo "usage: client_internet_access {grant|revoke|status} mac_address (username)" ;;
esac
exit 0

