#!/bin/bash

export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export SHARED=$CURRENT_PATH/../../shared
export HOME=$CURRENT_PATH/../..
. $HOME/../.bashrc
. $HOME/../.profile
cd $SHARED
export SHARED=`pwd`
cd $CURRENT_PATH
case $1 in
   update)
      bundle exec whenever --update-crontab dashboard
      ;;
    clear)
      bundle exec whenever --clear-crontab dashboard
      ;;
    *)  
      echo "usage: cron {update|clear}" ;;
esac
exit 0