#!/bin/bash

# start hostapd manually in foreground:
# sudo /usr/local/bin/hostapd -d -P ~/dashboard/shared/pids/hostapd.pid ~/dashboard/shared/config/hostapd.d/config

export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export SHARED=$CURRENT_PATH/../../shared
export HOME=$CURRENT_PATH/../..
. $HOME/../.bashrc
. $HOME/../.profile

export INTERFACE=$2
export PIDFILE=$CURRENT_PATH/tmp/pids/dnsmasq_$INTERFACE.pid

cd $SHARED
export SHARED=`pwd`
export CONFIG_FILE=$SHARED/config/dnsmasq.d/$INTERFACE
echo $CONFIG_FILE
case $1 in
   start)
      start-stop-daemon --stop --pidfile $PIDFILE
      start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --background --exec /usr/sbin/dnsmasq -- -C $CONFIG_FILE -k
      ;;
    stop)
      start-stop-daemon --stop --pidfile $PIDFILE
      ;;
    status)
      kill -0 `cat $PIDFILE`
      if [ $? != 0 ]; then
        echo "DNS for $INTERFACE is not running."
        exit 1
      else
        echo "DNS for $INTERFACE is running."
        exit 0
      fi
      ;;
    *)  
      echo "usage: dnsmasq rails-app-path {start|stop|status} interface" ;;
esac
exit 0