#!/bin/bash

export NODE_PORT=8124
export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export HOME=$CURRENT_PATH/../..
. $HOME/../.bashrc
. $HOME/../.profile
cd $CURRENT_PATH
case $1 in
   start)
      exec 2>&1 /usr/local/bin/node $CURRENT_PATH/node/node.js port=$NODE_PORT 1>$CURRENT_PATH/log/node.log &
      ;;
    stop)  
      kill `cat $CURRENT_PATH/tmp/pids/node_$NODE_PORT.pid` ;;
    *)  
      echo "usage: node rails-app-path {start|stop}" ;;
esac
exit 0
