#!/usr/bin/env ruby

require 'rubygems'
gem 'daemons'
require 'daemons'

# Assumes the scrip is located in a subdirectory of the Rails root directory
rails_root = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))

puts "RAILS ROOT #{rails_root}"

Daemons.run_proc(File.basename($0), :dir_mode => :normal, :dir => File.join(rails_root, 'log'), :force_kill_wait => 30) do
  require File.join(rails_root, 'config', 'environment')

  # Use the default queue settings.
  queue = Sunspot::IndexQueue.new

  # Don't want the daemon to fill up the log with SQL queries in development mode
  Rails.logger.level = Logger::INFO if Rails.logger.level == Logger::DEBUG

  loop do
    begin
      queue.process
      sleep(2)
    rescue Exception => e
      # Make sure we can exit the loop on a shutdown
      raise e if e.is_a?(SystemExit) || e.is_a?(Interrupt)
      # If Solr isn't responding, wait a while to give it time to get back up
      if e.is_a?(Sunspot::IndexQueue::SolrNotResponding)
        sleep(30)
      else
        Rails.logger.error(e)
      end
    end
  end
end

