#!/bin/bash
# this only for production use

export CURRENT_PATH=$1
export HOME=$CURRENT_PATH/../..
shift 1
. $HOME/../.bashrc
. $HOME/../.profile
cd $CURRENT_PATH
case $1 in
   start)
      bundle exec sunspot-solr start -p 8983 -s $CURRENT_PATH/solr --pid-dir=$CURRENT_PATH/tmp/pids -d $CURRENT_PATH/../shared/system/solr/data
      ;;
    stop)
      bundle exec sunspot-solr stop  -p 8983 -s $CURRENT_PATH/solr --pid-dir=$CURRENT_PATH/tmp/pids -d $CURRENT_PATH/../shared/system/solr/data
      ;;
    *)  
      echo "usage: solr {working directory} {start|stop}" ;;
esac
exit 0
