#!/bin/bash
# this only for production use

export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export HOME=$CURRENT_PATH/../..
. $HOME/.bashrc
. $HOME/.profile
. /usr/local/rvm/scripts/rvm
cd $CURRENT_PATH
case $1 in
   start)
      bundle exec sunspot-solr start -p 8983 -s $CURRENT_PATH/solr --pid-dir=$CURRENT_PATH/tmp/pids -d $CURRENT_PATH/../shared/solr/data
      ;;
    stop)
      bundle exec sunspot-solr stop  -p 8983 -s $CURRENT_PATH/solr --pid-dir=$CURRENT_PATH/tmp/pids -d $CURRENT_PATH/../shared/solr/data
      ;;
    *)  
      echo "usage: solr {working directory} {start|stop}" ;;
esac
exit 0
