#!/bin/bash

export CURRENT_PATH=$(cd `dirname $0` && cd ../.. && pwd)
export SHARED=$CURRENT_PATH/../shared
export HOME=$CURRENT_PATH/../..
. $HOME/../.bashrc
. $HOME/../.profile
cd $SHARED
export SHARED=`pwd`
case $1 in
   start)
      /usr/local/bin/hostapd -P $SHARED/pids/hostapd.pid -B $SHARED/config/hostapd.d/config
      sleep 10
      ifup --force wlan0
      ifup --force wlan1
      ;;
    stop)  
      ifdown --force wlan0
      ifdown --force wlan1
      kill `cat $SHARED/pids/hostapd.pid`
      ;;
    status)
      kill -0 `cat $SHARED/pids/hostapd.pid`
      if [ $? != 0 ]; then
        echo "Hostapd is not running."
        exit 1
      else
        echo "Hostapd is running."
        exit 0
      fi
      ;;
    *)  
      echo "usage: wifi {start|stop|status}" ;;
esac
exit 0
