#!/bin/bash

export CURRENT_PATH=$1
export SHARED=$CURRENT_PATH/../shared
export HOME=$CURRENT_PATH/../..
shift 1
. $HOME/../.bashrc
. $HOME/../.profile
cd $SHARED
export SHARED=`pwd`
case $1 in
   start)
      /usr/local/bin/hostapd -P $SHARED/pids/hostapd.pid -B $SHARED/config/hostapd.d/config
      ;;
    stop)  
      kill `cat $SHARED/pids/hostapd.pid`
      ;;
    status)
      kill -0 `cat $SHARED/pids/hostapd.pid`
      ;;
      
    *)  
      echo "usage: wifi rails-app-path {start|stop|status}" ;;
esac
exit 0
