default:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/protonet/application.js
    # - app/javascripts/**/*.js
instruments:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/protonet/pages/instruments.js
snapshots:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/protonet/pages/snapshots.js
files:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/protonet/pages/files.js
users:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/protonet/pages/users.js
preferences:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/protonet/pages/preferences.js
meeps:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/protonet/pages/meeps.js
invitations:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/lib/wysihtml5/dist/wysihtml5-0.3.0_rc1.js
    - app/javascripts/protonet/pages/invitations.js
unittest:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - test/javascripts/protonet/protonet.js
en:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - config/locales/en.js