default:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js
    # - app/javascripts/**/*.js
instruments:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js
    - app/javascripts/instruments.js
files:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js
    - app/javascripts/files.js
users:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js
    - app/javascripts/users.js
channels:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js
    - app/javascripts/channels.js
preferences:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js
    - app/javascripts/preferences.js
networks:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js
    - app/javascripts/networks.js
sessions:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js