default:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/application.js
    # - app/javascripts/**/*.js
instruments:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/instruments.js
snapshots:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/snapshots.js
files:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/files.js
users:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/users.js
preferences:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/preferences.js
meeps:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/meeps.js
invitations:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/invitations.js
search:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/search.js
channels:
  asset_root: public
  load_path:
    - app/javascripts
    - vendor/sprockets/*/src
    - vendor/plugins/*/javascripts
  source_files:
    - app/javascripts/pages/channels.js