production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO

test: &test
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
  auto_commit_after_request: true
cucumber:
  <<: *test
