#!/usr/bin/env ruby

require 'mysql'
require 'uri'
require 'yaml'

# scan once a day
SCAN_INTERVAL   = 1 * 24 * 60 * 60
RAILS_ROOT      = "~/dashboard/current"
LOG_FILE        = "~/dashboard/current/log/clamscan_error.log"
DB_CONFIG_FILE  = "~/dashboard/current/config/database.yml"
FILES_DIR       = "~/"

db_config = YAML::load(File.read(DB_CONFIG_FILE))
connection = Mysql.new(db_config['production']['host'], db_config['production']['username'], db_config['production']['password'], db_config['production']['database'])
result = connection.query("SELECT * FROM system_preferences WHERE var = 'last_clamav_scan'")

last_clamav_scan = 0
result.each_hash {|h| last_clamav_scan = h['value'].to_i }

puts "last virus scan: #{Time.at(last_clamav_scan)}"
if last_clamav_scan + SCAN_INTERVAL < Time.now.to_i
  if result.num_rows > 0
    connection.query("UPDATE system_preferences SET value = '#{Time.now.to_i}' WHERE var = 'last_clamav_scan'")
  else
    connection.query("INSERT INTO system_preferences (var, value) VALUES ('last_clamav_scan', '#{Time.now.to_i}')")
  end
  
  puts "refresh virus db"
  `freshclam 2>> #{LOG_FILE}`
  # code 0 => success
  # code 52 => network connection problem (no internet connection?)
  # find all error codes here: http://linux.die.net/man/1/freshclam
  freshclam_code = $?.exitstatus
  
  puts "perform scan"
  details = `clamscan -i -r #{FILES_DIR} 2>> #{LOG_FILE}`
  # code 0 => no virus found
  # code 1 => virus found
  # code 2 => error
  # http://linux.die.net/man/1/clamscan
  code = $?.exitstatus
  
  puts "clamscan return code: #{code}"
  
  `cd #{RAILS_ROOT} && RAILS_ENV=production bundle exec rake report:virus_scan code=#{code} freshclam_code=#{freshclam_code} details="#{URI.escape(details)}"`
end

connection.close
