#!/bin/bash

if [ -f ~/.bashrc ]
then
  . ~/.bashrc
fi
if [ -f ~/.profile ]
then
  . ~/.profile
fi

cd .
bundle exec passenger start --max-pool-size 1 --spawn-method conservative --nginx-config config/nginx_local.erb