#!/usr/bin/expect

log_file -noappend /tmp/ptn_update_migrations.log

# never time out
set timeout -1
set password [lindex $argv 0]

# This spawns the babushka protonet migration
spawn bash
exp_send "source /home/protonet/.bashrc\n"
exp_send "source /home/protonet/.profile\n"
exp_send "babushka protonet:up.migration\n"

# The script expects Password any number of times and answers with the correct password
expect {
  -re "\[Pp]assword.*:"  {
    send "$password\r"
    exp_continue
  }
}

# puts $expect_out(buffer)
log_file

# call like script/ptn_babushka_migrations PASSWORD make sure to do a export HISTIGNORE="*ptn_babushka_migrations*" to make sure the command is not stored in the shell history

