#!/bin/bash

export SHARED_PATH=$1
export HOME=$SHARED_PATH/../..
shift 1
. $HOME/.bashrc
. $HOME/.profile

cd $HOME/deploy
git reset --hard
git checkout master
git pull

# git co 20de6c3a36a97183cdb58836fc9b831e9c77926c
# bin/deploy -r protonet -e production -m deploy -c $SHARED_PATH/config/protonet.d/deploy_config 2>&1 > /tmp/ptn_release_update

bundle check 2>&1 > /dev/null ; if [ $? -ne 0 ] ; then sh -c "bundle install --without test" ; fi
bundle exec bin/deploy -r protonet -e production -m deploy -c $SHARED_PATH/config/protonet.d/deploy_config 2>&1 > /tmp/ptn_release_update
