#!/usr/bin/expect

log_file /tmp/ptn_release_update.log
proc do_exit {msg} {
    puts stderr $msg
    exit 1
}

send_log "[exec date] starting ptn_deployer_update\n"

# never time out
set timeout -1

# This spawns the babushka protonet migration
spawn babushka "protonet:app deployer update"
set license [lindex $argv 0]
# The script expects Password any number of times and answers with the correct password
expect {
  -re ".*Please enter your protonet license key.*\?"  {
    send "$license\r"
    exp_continue
  }
  -re ".*file a bug report for that now*\? " {
    send "n\r"
    do_exit "deployer update failed"
  }
}
# puts $expect_out(buffer)
log_file

# call like script/ptn_deployer_update LICENSEKEY make sure to do a export HISTIGNORE="*ptn_babushka_update*" to make sure the command is not stored in the shell history