#!/bin/bash

export RELEASE_VERSION=""
export RELEASE_VERSION_PATH="/$RELEASE_VERSION"

# the following is highly inspired and partly copied by what benhoskings is doing with his babushka bootstrapping script

function has {
  type "$1" >/dev/null 2>&1
}

function welcome {
  echo ""
  echo "Good morning 'nam!"
  echo ""
  echo "This is your protonet bootstrapping script speaking, if all goes well today"
  echo "we should have your node up and running in no time."
  echo ""
  echo "DISCLAIMER: this is intended to be run on Ubuntu 10.04LTS server releases "
  echo "so don't blame us if it doesn't work on something else."
  echo ""
  echo "Let's have a short overview of what we're going to do:"
  echo "- we start with creating the protonet user, the admin group which it will belong to"
  echo "- next up we'll get ruby and our basic building stuff"
  echo "- will then switch to the protonet user and install ourselves a babushka"
  echo "- next up we'll be getting our babushka deps that will handle the rest of the installation"
  echo ""
  echo "If everything goes according to plan you'll end up with a perfectly setup protonet node."
  echo ""
  echo "So let's roll!"
  echo ""
  read -p "Ready? [y/N] " f
  [[ "$f" == y* ]] || [[ "$f" == Y* ]]
}

function user_basics {
  echo ""
  echo "Setting up user..."
  id -u protonet >/dev/null 2>&1

  if [ $? != 0 ]; then 
    #Make sure that we have a protonet user
    sudo useradd protonet -m -s /bin/bash
    #Make sure there is a protonet group
    sudo groupadd -f admin
    # add the current user to the admin group
    sudo usermod -a -G admin `whoami`
    # And add the protonet user to that group
    sudo usermod -a -G admin protonet
    sudo usermod -a -G sudo protonet
    echo "Setup password for protonet user:"
    sudo passwd protonet
    # setup password for protonet
  fi
  echo "Done setting up user."
  echo ""
}

function update_apt {
  echo ""
  echo "Updating apt..."
  sudo apt-get -qqy update
  echo "Done updating apt."
  echo ""
}

function install_rvm {
  echo ""
  echo "Installing rvm system-wide..."
  if ! has 'rvm'; then
    sudo /usr/bin/apt-get install -qqy build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion
    
    sudo bash -s stable < <( curl -L -s -k get.rvm.io )
    sudo usermod -a -G rvm `whoami`
    sudo usermod -a -G rvm protonet
    sudo usermod -a -G rvm root
    echo "finished rvm"
  else
    echo "Already there... moving on."
  fi
  echo "Done installing rvm."
  echo ""
}

function install_ruby {
  echo ""
  echo "Installing ruby..."
  if ! has 'ruby'; then
    source /etc/profile.d/rvm.sh
    sg rvm "rvm install 1.9.3-p125"
    sg rvm "rvm alias create default 1.9.3-p125"
    source /usr/local/rvm/scripts/rvm
  else
    echo "Already there... moving on."
  fi
  echo "Done installing ruby."
  echo ""
}

function continue_installation {
 echo "continue installation"
 sudo su -l protonet -c "`wget -O - http://releases.protonet.info/bootstrap-continue$RELEASE_VERSION_PATH`"
}

function logo {
  echo "    _   ,_    __ _|_  __   _  _    _ _|_ "
  echo "  |/ \_/  |  /  \_|  /  \_/ |/ |  |/  |  "
  echo "  |__/    |_/\__/ |_/\__/   |  |_/|__/|_/"
  echo " /|                                      "
  echo " \|                                      "
  echo ""
}

function on_install_success {

  echo ""
  echo "Success!!"
  echo ""
  true
}

function on_install_failure {
  echo ""
  echo "Something went wrong during the install."
  echo ""
  false
}

if welcome; then
  echo "Excellent."
  echo ""
  user_basics && 
  update_apt &&
  install_rvm &&
  install_ruby &&
  continue_installation &&
  on_install_success || on_install_failure
else
  echo ""
  echo "OK, maybe another time. :)"
fi