#!/bin/bash

SERVER="releases.protonet.info"
RELEASE_VERSION=""

echo "Continuing bootstrapping..."

function has {
  type "$1" >/dev/null 2>&1
}

function get_babushka {
  bash -c "`wget -O - $SERVER/bootstrap-babushka$RELEASE_VERSION`"
}

function check_licence_key() {
  echo ""
  read -p "Please enter your protonet license key: " f
  LICENCE_KEY="`echo $f | tr -d '\n'`"
  if has 'curl'; then
    curl -f http://$SERVER/licence/check/$LICENCE_KEY
  elif has 'wget'; then
    wget -q --server-response http://$SERVER/licence/check/$LICENCE_KEY -o /dev/null -O /dev/null
  fi
}

function get_babushka_deps() {
  echo ""
  local FILE=/tmp/babushka_deps.tar.gz
  if has 'curl'; then
    curl -f http://$SERVER/release/babushka-deps/get/$f -o $FILE
  elif has 'wget'; then
    wget -q http://$SERVER/release/babushka-deps/get/$f -O $FILE
  fi
  cd /tmp
  tar -xzf $FILE
  rm -rf /home/protonet/.babushka/sources/dudemeister
  mkdir -p /home/protonet/.babushka/sources/dudemeister
  mv /tmp/babushka-deps /home/protonet/.babushka/sources/dudemeister
  rm -rf $FILE
}

function get_babushka_protonet() {
  babushka "dudemeister:protonet babushka"
  . ~/.profile
}

function install() {
  echo ""
  echo "If you are about to run protonet on your own hardware or virtual machine please select 1"
  echo "If you want it to be installed on a real protonet provided node select 2"
  echo "1. vm preps"
  echo "2. full node preps"
  read -p "Your selection: " t
  if [ $t == 1 ]; then
    babushka protonet:vm-preparations
  elif [ $t == 2 ]; then
    babushka protonet:node-preparations
  else
    exit 1
  fi
}

get_babushka &&
check_licence_key &&
get_babushka_deps &&
get_babushka_protonet &&
install