#!/usr/bin/expect

log_file -noappend /tmp/ptn_update_migrations.log
proc do_exit {msg} {
    puts stderr $msg
    exit 1
}

# never time out
set timeout -1
set password [lindex $argv 0]

# This spawns the babushka protonet migration
spawn bash -l
exp_send "source /home/protonet/.bashrc\n"
exp_send "source /home/protonet/.profile\n"
exp_send "unset RUBYOPT;unset GEM_HOME; unset GEM_PATH; unset BUNDLE_GEMFILE\n"
exp_send "export GEM_PATH=`which ruby|sed -e 's/bin\\/ruby/lib\\/ruby\\/gems\\/1.8/'`\n"
exp_send "export GEM_HOME=`which ruby|sed -e 's/bin\\/ruby/lib\\/ruby\\/gems\\/1.8/'`\n"
exp_send "babushka protonet:up.migration\n"
exp_send "exit\n"

# The script expects Password any number of times and answers with the correct password
expect {
  -re "\[Pp]assword.*:"  {
    send "$password\r"
    exp_continue
  }
  -re ".*password for.*:" {
    send "$password\r"
    exp_continue
  }
  -re "protonet@.*\$" {
    send "exit\r"
    exp_continue
  }
  -re ".*file a bug report for that now*\? " {
    send "n\r"
    do_exit "babushka migration failed"
  }
}

# puts $expect_out(buffer)
log_file

# call like script/ptn_babushka_migrations PASSWORD make sure to do a export HISTIGNORE="*ptn_babushka_migrations*" to make sure the command is not stored in the shell history

