#!/usr/bin/expect

log_file /tmp/ptn_release_update.log
proc do_exit {msg} {
    puts stderr $msg
    exit 1
}

send_log "[exec date] starting ptn_babushka_migrations\n"

# never time out
set timeout -1
set password [lindex $argv 0]

# This spawns the babushka protonet migration
spawn bash -l
exp_send "source /home/protonet/.bashrc\n"
exp_send "source /home/protonet/.profile\n"
exp_send "source /usr/local/rvm/scripts/rvm"
exp_send "babushka protonet:up.migration\n"
exp_send "exit\n"

# The script expects Password any number of times and answers with the correct password
expect {
  -re "\[Pp]assword.*:"  {
    send "$password\r"
    exp_continue
  }
  -re ".*password for.*:" {
    send "$password\r"
    exp_continue
  }
  -re "protonet@.*\$" {
    send "exit\r"
    exp_continue
  }
  -re ".*running migration number.*failed! aborting" {
    do_exit "babushka migration failed"
  }
  -re ".*file a bug report for that now*\? " {
    send "n\r"
    do_exit "babushka migration failed"
  }
}

# puts $expect_out(buffer)
log_file

# call like script/ptn_babushka_migrations PASSWORD make sure to do a export HISTIGNORE="*ptn_babushka_migrations*" to make sure the command is not stored in the shell history

