#!/usr/bin/expect
log_file -noappend /tmp/ptn_check_password.log

proc do_exit {msg} {
    puts stderr $msg
    exit 1
}

# never time out
set timeout -1

# This spawns the babushka protonet migration
spawn sudo ls
set password [lindex $argv 0]
# The script expects Password any number of times and answers with the correct password
expect {
  -re "\[Pp]assword.*:"  {
    send "$password\r"
    exp_continue
  }
  "Sorry, try again." {
      do_exit "incorrect password"
  }
}
# puts $expect_out(buffer)
log_file

# call like script/ptn_check_password PASSWORD make sure to do a export HISTIGNORE="*ptn_check_password*" to make sure the command is not stored in the shell history

