#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

# THIS IS NEW:
if defined?(Rails::Server)
  require "rails/commands/server"
  module Rails
    class Server
      def start
        begin
          if self.options[:environment] != "production"
            # this is set here for all environments beside production since the port is set dynamically there
            port_file_path = "#{Rails.root}/tmp/app_port_#{self.options[:environment]}"
            port_number = self.options[:Port]
            File.open(port_file_path, 'w') {|f| f.write(port_number)}
            configatron.web_app_port = port_number
            at_exit { File.delete(port_file_path) }
          end
        rescue
          nil
        end
        super
      end
    end
  end
end
# END OF CHANGE

require 'rails/commands'
